stages:
  preprocess:
    cmd: python3 src/preprocess.py
    deps:
    - data/Reviews.csv
    - src/preprocess.py
    outs:
    - data/processed.csv
  train:
    cmd: python3 src/train.py
    deps:
    - data/processed.csv
    - src/train.py
    outs:
    - models/model.pkl
    - models/vectorizer.pkl
